---
title: "PLS & CART"
author: "Marjete Vucinaj"
date: "2024-12-11"
output: html_document
---

```{r setup, include=FALSE}

set.seed(8675309)
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(pls)
library(magrittr)
library(tidyverse)
library(caret)
library(rpart)
```

Response Variable.: pH

```{r}
imputed_data <- read_csv("imputed_test_data.csv")
head(imputed_data)

```


```{r}
# Split

train_index <- createDataPartition(imputed_data$PH, p = 0.75, list = FALSE)
train_data <- imputed_data[train_index, ]
test_data <- imputed_data[-train_index, ]

```

```{r}
# pls can handle multicollinearity but just checking
correlation <- cor(train_data$PH, train_data[, -which(names(train_data) == "PH")])
print(correlation)

```
```{r}
trainX <- train_data[, -which(names(train_data) == "PH")]  
trainY <- train_data$PH  

trainX <- as.data.frame(trainX)
trainY <- as.numeric(trainY)
```


```{r}
plsTune_model <- train(
  x = trainX, 
  y = trainY,
  method = "pls", 
  tuneLength = 10, 
  trControl = trainControl(method = "cv"),  
)
# removed - preProc = c("center", "scale"); was already applied in imputation code
print(plsTune_model)
#suppress or address warning?
```

```{r}
optimal_components <- 7
pls_final_model <- plsr(PH ~ ., data = train_data, ncomp = optimal_components)
```

```{r}
predictions <- predict(pls_final_model, newdata = test_data, ncomp = optimal_components)
rmse <- sqrt(mean((test_data$PH - predictions)^2))
r_squared <- cor(test_data$PH, predictions)^2
mae <- mean(abs(test_data$PH - predictions))

cat("Test RMSE:", rmse, "\n")
cat("Test R²:", r_squared, "\n")
cat("Test MAE:", mae, "\n")

```

CART: Regression: response variable is numerical and continuous.



```{r}
cart_model <- train(
  PH ~ ., 
  data = train_data,
  method = "rpart",
  trControl = trainControl(method = "cv", number = 3, verboseIter = TRUE), 
  tuneLength = 10
)

```

```{r}
print(cart_model)
print(cart_model$bestTune)  
```
```{r}

best_cp <- cart_model$bestTune$cp

cart_final_model <- rpart(PH ~ ., data = train_data, method = "anova", control = rpart.control(cp = best_cp))

cart_predictions <- predict(cart_final_model, newdata = test_data)

cart_rmse <- sqrt(mean((test_data$PH - cart_predictions)^2))
cart_r_squared <- cor(test_data$PH, cart_predictions)^2
cart_mae <- mean(abs(test_data$PH - cart_predictions))

cat("CART Test RMSE:", cart_rmse, "\n")
cat("CART Test R²:", cart_r_squared, "\n")
cat("CART Test MAE:", cart_mae, "\n")

```



Question: We wait to predict on the best model?
